// counter.js
const COUNTER_INCREMENT_COUNTER = 'INCREMENT_COUNTER';
const COUNTER_DECREMENT_COUNTER = 'DECREMENT_COUNTER';

// userState.js
const USERSTATE_IS_LOGGED_IN = 'USERSTATE_IS_LOGGED_IN';

export {
    COUNTER_INCREMENT_COUNTER,
    COUNTER_DECREMENT_COUNTER,

    USERSTATE_IS_LOGGED_IN,
}
